namespace PhotoshopUtilities
{
	partial class HistogramPlotter : System.Windows.Forms.UserControl
	{
		#region Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.grpHistogram		=  new MyControls.MyGroupBox();
			this.thePlotSurface2D	=  new NPlot.Windows.PlotSurface2D();
			this.stInfo				=  new System.Windows.Forms.Label();
			this.stMean				=  new System.Windows.Forms.Label();
			this.stStdDev			=  new System.Windows.Forms.Label();
			this.stMedian			=  new System.Windows.Forms.Label();
			this.stDelta			=  new System.Windows.Forms.Label();

			this.grpHistogram.SuspendLayout();
			this.SuspendLayout();

			// 
			// thePlotSurface2D
			// 
			this.thePlotSurface2D.AutoScaleAutoGeneratedAxes = false;
			this.thePlotSurface2D.AutoScaleTitle = false;
			this.thePlotSurface2D.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.thePlotSurface2D.DateTimeToolTip = false;
			this.thePlotSurface2D.Legend = null;
			this.thePlotSurface2D.LegendZOrder = -1;
			this.thePlotSurface2D.Location = new System.Drawing.Point( 16, 24 );
			this.thePlotSurface2D.Name = "thePlotSurface2D";
			this.thePlotSurface2D.RightMenu = null;
			this.thePlotSurface2D.ShowCoordinates = true;
			this.thePlotSurface2D.Size = new System.Drawing.Size( 388, 206 );
			this.thePlotSurface2D.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			this.thePlotSurface2D.TabIndex = 0;
			this.thePlotSurface2D.Title = "Histogram";
			this.thePlotSurface2D.TitleFont = new System.Drawing.Font( "Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel );
			this.thePlotSurface2D.XAxis1 = null;
			this.thePlotSurface2D.XAxis2 = null;
			this.thePlotSurface2D.YAxis1 = null;
			this.thePlotSurface2D.YAxis2 = null;
			// 
			// stMean
			// 
			this.stMean.Location = new System.Drawing.Point( 30, 250 );
			this.stMean.Name = "stMean";
			this.stMean.Size = new System.Drawing.Size( 80, 14 );
			this.stMean.TabIndex = 1;
			this.stMean.Text = "Mean:  ";
			// 
			// stMedian
			// 
			this.stMedian.Location = new System.Drawing.Point( 125, 250 );
			this.stMedian.Name = "stMedian";
			this.stMedian.Size = new System.Drawing.Size( 80, 14 );
			this.stMedian.TabIndex = 2;
			this.stMedian.Text = "Median:  ";
			// 
			// stStdDev
			// 
			this.stStdDev.Location = new System.Drawing.Point( 220, 250 );
			this.stStdDev.Name = "stStdDev";
			this.stStdDev.Size = new System.Drawing.Size( 80, 14 );
			this.stStdDev.TabIndex = 3;
			this.stStdDev.Text = "Std Dev:  ";
			// 
			// stDelta
			// 
			this.stDelta.Location = new System.Drawing.Point( 325, 250 );
			this.stDelta.Name = "stDelta";
			this.stDelta.Size = new System.Drawing.Size( 80, 14 );
			this.stDelta.TabIndex = 3;
			this.stDelta.Text = "Delta:  ";
			// 
			// stInfo
			// 
			this.stInfo.Location = new System.Drawing.Point( 122, 276 );
			this.stInfo.Name = "stInfo";
			this.stInfo.Size = new System.Drawing.Size( 180, 14 );
			this.stInfo.TabIndex = 7;
			this.stInfo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.stInfo.Text = "Status Info";
			// 
			// grpHistogram
			// 
			this.grpHistogram.Controls.Add( this.thePlotSurface2D );
			this.grpHistogram.Controls.Add( this.stDelta );
			this.grpHistogram.Controls.Add( this.stStdDev );
			this.grpHistogram.Controls.Add( this.stMedian );
			this.grpHistogram.Controls.Add( this.stMean );
			this.grpHistogram.Controls.Add( this.stInfo );
			this.grpHistogram.Location = new System.Drawing.Point( 0, 0 );
			this.grpHistogram.Name = "grpHistogram";
			this.grpHistogram.Size = new System.Drawing.Size( 420, 304 );
			this.grpHistogram.TabIndex = 5;
			this.grpHistogram.TabStop = false;
			this.grpHistogram.Text = "Histogram";

			this.Controls.Add( this.grpHistogram );
			this.grpHistogram.ResumeLayout( false );
			this.ResumeLayout( false );
		}
		#endregion

		private MyControls.MyGroupBox		grpHistogram;
		public System.Windows.Forms.Label	stInfo;
		public System.Windows.Forms.Label	stMean;
		public System.Windows.Forms.Label	stStdDev;
		public System.Windows.Forms.Label	stMedian;
		public System.Windows.Forms.Label	stDelta;
		public NPlot.Windows.PlotSurface2D	thePlotSurface2D;
	}
}
